# nginx-mng/tasks/conf_setup.yml
---
- name: 创建systemd管理
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx@{{ inventory_hostname }}.service
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  notify: 
    - daemon_reload
    - restart nginx

- name: 设置开机启动nginx
  systemd:
    name: nginx@{{ inventory_hostname }}
    enabled: yes
  become: yes

- name: 配置 nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_install_dir }}/conf/nginx.conf"
    mode: '0644'
  notify: 
    - validate nginx config
    - reload nginx

- name: 创建conf.d目录
  file:
    path: "{{ nginx_install_dir }}/conf/conf.d"
    state: directory
    mode: '0755'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: 配置 conf.d/nginx.conf
  template:
    src: "{{ inventory_hostname }}-nginx.conf.j2"
    dest: "{{ nginx_install_dir }}/conf/conf.d/nginx.conf"
    mode: '0644'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify:
    - validate nginx config
    - reload nginx
  ignore_errors: yes