# nginx-mng/tasks/install_dependencies.yml
---
- name: 启用 EPEL 仓库
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install required packages for CentOS/RHEL
  yum:
    name:
      - gcc
      - gcc-c++
      - make
      - openssl-devel
      - pcre-devel
      - zlib-devel
      - libxml2-devel
      - libxslt-devel
      - gd-devel
      - perl-ExtUtils-Embed
    state: present
  when: ansible_os_family == "RedHat"

- name: Install required packages for Ubuntu/Debian
  apt:
    name:
      - build-essential
      - libpcre3-dev
      - libssl-dev
      - zlib1g-dev
      - libxml2-dev
      - libxslt1-dev
      - libgd-dev
      - libperl-dev
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Create Nginx group
  group:
    name: "{{ nginx_group }}"
    state: present
  
- name: Create Nginx user
  user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
#    system: yes
    shell: /sbin/nologin
    create_home: no