# nginx-mng/tasks/main.yml
---
- name: pre 获取 nginx 版本信息
  import_tasks: pre_nginx_version.yml
  tags: [install,uninstall,config,upgrade,rollback]
  #tags: [test]

- name: 初始化安装环境
  import_tasks: init_sys.yml
  tags: [install]

- name: 编译安装 nginx
  import_tasks: compile_install.yml
  tags: [install]
  when: current_nginx_version.rc != 0

- name: 配置管理
  import_tasks: conf_setup.yml
  tags: [config]

- name: 升级 nginx 版本
  import_tasks: upgrade_nginx.yml
  tags: [upgrade]
  when: current_nginx_version.stdout is version_compare(nginx_version, '<')

- name: 回滚 nginx 版本
  import_tasks: rollback_nginx.yml
  tags: [rollback]

- name: after 获取 nginx 版本信息
  import_tasks: after_nginx_version.yml
  tags: [install,uninstall,config,upgrade,rollback]