# nginx-mng/tasks/main.yml
---
- name: pre 获取 nginx 版本信息
  import_tasks: get_version.yml
  tags: [always]
  #tags: [debug]

- name: 初始化安装环境
  import_tasks: init.yml
  tags: [install]

- name: 编译安装 nginx
  import_tasks: install.yml
  tags: [install]
  when: current_nginx_version.rc != 0

- name: 卸载nginx
  import_tasks: uninstall.yml
  tags: [uninstall]
  when: current_nginx_version.rc == 0

- name: 服务管理
  import_tasks: server.yml
  tags: [install,config,upgrade,rollback]

- name: 配置管理
  import_tasks: config.yml
  tags: [config]

- name: 升级 nginx 版本
  import_tasks: upgrade.yml
  tags: [upgrade]
  when: current_nginx_version.stdout is version_compare(nginx_version, '<')

- name: 回滚 nginx 版本
  import_tasks: rollback.yml
  tags: [rollback]

- name: after 获取 nginx 版本信息
  import_tasks: check_version.yml
  tags: [always]