- name: 获取并提取当前nginx版本信息(如果已经存在)
  shell: |
    {{ nginx_install_dir }}/sbin/nginx -v 2>&1 | grep -oP 'nginx/\K[0-9.]+'
  register: current_nginx_version
  changed_when: false
  ignore_errors: yes

- name: 创建保存版本日志目录文件
  file:
    path: "{{ version_log_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"

- name: 获取当前时间
  set_fact:
    current_time: "{{ ansible_date_time.date }}-{{ (ansible_date_time.hour | int + 8) % 24 }}_{{ ansible_date_time.minute }}_{{ ansible_date_time.second }}"

- name: 将 Nginx 版本信息记录到文本文件
  ansible.builtin.lineinfile:
    path: "{{ version_log_file }}"
    line: "{{ current_time }} - {{ ansible_run_tags }} - pre: {{ current_nginx_version.stdout }}"
    create: yes