# mysql 逻辑数据备份
- block: 
  - name: 数据备份脚本
    template:
      src: "{{ service }}/backup.sh.j2"
      dest: "{{ backup_dir }}/backup.sh"
      mode: '0755'

  - name: 执行一次备份任务
    shell: "{{ backup_dir }}/backup.sh"
    become: yes
  
  - name: 添加定时任务
    cron:
      name: "{{ service }}-{{ inventory_hostname }} 备份任务"
      job: "{{ backup_dir }}/backup.sh"
      minute: "{{ backup_cron_schedule.split()[0] }}"
      hour: "{{ backup_cron_schedule.split()[1] }}"
      day: "{{ backup_cron_schedule.split()[2] }}"
      month: "{{ backup_cron_schedule.split()[3] }}"
      weekday: "{{ backup_cron_schedule.split()[4] }}"
      user: root
  when: service == "mysql"