
- name: 获取并提取当前版本信息(如果已经存在)
  shell: |
    {{ install_dir }}/sbin/nginx -v 2>&1 | grep -oP 'nginx/\K[0-9.]+'
  register: after_version
  changed_when: false
  ignore_errors: yes
  when: service == "nginx"

- name: 获取并提取当前版本信息(如果已经存在)
  shell: |
    {{ install_dir }}/bin/mysqld -V 2>&1 |  awk '{print $3}'
  register: after_version
  changed_when: false
  ignore_errors: yes
  when: service == "mysql"

- block: # 输出结果
    - name: 将版本信息记录到文本文件
      ansible.builtin.lineinfile:
        path: "{{ version_log_dir }}/version.log"
        line: "{{ current_time }} - {{ ansible_run_tags }} - after: {{ after_version.stdout }}\n"
        create: yes
