---
- block: 
  - name: 配置 nginx.conf
    template:
      src: "{{ ex_service }}/nginx.conf.j2"
      dest: "{{ install_dir }}/conf/nginx.conf"
      mode: '0644'

  - name: 创建相关目录
    file:
      path: "{{ install_dir }}/conf/conf.d"
      state: directory
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755

  - name: 配置 conf.d/nginx.conf
    template:
      src: "{{ ex_service }}/{{ inventory_hostname }}-nginx.conf.j2"
      dest: "{{ install_dir }}/conf/conf.d/nginx.conf"
      mode: '0644'
      owner: "{{ user }}"
      group: "{{ group }}"
  notify:
    - restart
  ignore_errors: yes
  when: ex_service == "nginx"

# mysql
- block: 
  - name: 生成MySQL配置文件
    template:
      src: "{{ ex_service }}/my.cnf.j2"
      dest: "{{ conf_dir }}/my.cnf"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644
    notify: restart
  when: ex_service == "mysql"

# haproxy
- block: 
  - name: 生成haproxy配置文件
    template:
      src: "{{ ex_service }}/haproxy.cfg.j2"
      dest: "{{ conf_dir }}/haproxy.cfg"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644
    notify: restart
  when: ex_service == "haproxy"