- name: 回滚软链接更新
  file:
    src: "{{ install_dir | dirname }}/{{ version }}"
    dest: "{{ install_dir }}"
    state: link
    force: yes

- name: 重启服务
  block:
    - name: Restart 
      service:
        name: "{{ ex_service }}@{{ inventory_hostname }}"
        state: restarted
      become: yes
    
    - name: Verify service status
      service:
        name: "{{ ex_service }}@{{ inventory_hostname }}"
        state: started
      become: yes