---
- name: 停止服务
  systemd:
    name: "{{ service }}@{{ inventory_hostname }}"
    state: stopped
  ignore_errors: yes

- name: 卸载前备份
  include_tasks: backup.yml

- name: 删除相关目录
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ install_dir }}" 
  - "{{ conf_dir }}" 
  - "{{ log_dir }}"

- name: 数据目录重命名
  shell: "mv {{ data_dir }} {{ data_dir }}_{{ current_time }}_bak"