---
- name: 升级前备份
  include_tasks: backup.yml

- name: 升级安装
  include_tasks: install.yml

- name: 清理过期备份数据
  shell: "ls -t {{ backup_dir }}/*.tar.gz | tail -n +{{ max_backups + 1 }} | xargs rm -f"
  changed_when: false