# 默认配置参数
mysql_version: 8.0.35
mysql_install_dir: "{{ mysql_install_root }}/{{ inventory_hostname }}"
#mysql_source_url: "https://dev.mysql.com/get/Downloads/MySQL-{{ mysql_version.split('.')[0] }}.{{ mysql_version.split('.')[1] }}/mysql-{{ mysql_version }}.tar.gz"
mysql_source_url: "https://cdn.mysql.com/archives/mysql-8.0/mysql-{{ mysql_version }}-linux-glibc2.12-x86_64.tar.xz"
mysql_service_name: "mysqld@{{ inventory_hostname }}"
mysql_config_path: "/etc/my{{ inventory_hostname }}.cnf"
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_data_dir: "/var/lib/mysql/{{ inventory_hostname }}"
mysql_port: 3306
mysql_bind_address: 0.0.0.0
mysql_databases: []
mysql_users: []

# 版本日志
version_log_dir: "/var/log/mysql-version"
version_log_file: "{{ version_log_dir }}/mysql-{{ inventory_hostname }}-version.log"

# 备份设置
mysql_backup_path: "/usr/local/mysql/backups"
mysql_max_backups: 10
backup_cron_schedule: "0 0 * * *"
backup_script_path: "/usr/local/mysql/backups"

# 编译依赖
build_dependencies:
  - gcc
  - cmake
  - ncurses-devel
  - openssl-devel
  - xz