# nginx-mng/defaults/main.yml
---
# Nginx version and download info
nginx_download_url: "http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
nginx_checksum_url: "{{ nginx_download_url }}.asc"
nginx_source_path: "/tmp"

# Installation paths
nginx_install_dir: "{{ nginx_install_root }}/{{ inventory_hostname }}"

# Compile options
nginx_configure_options: >
  --prefix={{ nginx_install_dir }}
  --user={{ nginx_user }}
  --group={{ nginx_group }}
  --with-http_ssl_module
  --with-http_v2_module
  --with-http_realip_module
  --with-http_stub_status_module
  --with-pcre
  --with-threads

# Backup settings
nginx_backup_path: "/usr/local/nginx/backups"
nginx_max_backups: 10

# Version management settings
version_log_dir: "/var/log/nginx_version_log"
version_log_file: "{{ version_log_dir }}/{{ inventory_hostname }}.log"