---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx@{{ inventory_hostname }}
    state: restarted
    enabled: yes