---
- name: 下载Nginx二进制包
  ansible.builtin.unarchive:
    src: https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    dest: /tmp
    remote_src: yes

- name: 编译安装Nginx
  ansible.builtin.command:
    chdir: /tmp/nginx-{{ nginx_version }}
    cmd: |
      ./configure --prefix={{ nginx_install_dir }}/{{ inventory_hostname }} \
                  --user=nginx \
                  --group=nginx \
                  --with-http_ssl_module \
                  --with-http_stub_status_module \
                  --with-stream \
                  --with-threads
      make
      make install
  register: install_result

- name: 获取实际安装版本
  ansible.builtin.command:
    cmd: "{{ nginx_install_dir }}/{{ inventory_hostname }}/sbin/nginx -v"
  register: nginx_version_check
  changed_when: false
  failed_when: nginx_version_check.rc != 0