# nginx-mng/tasks/compile_install.yml
---
- name: Download Nginx source
  get_url:
    url: "{{ nginx_download_url }}"
    dest: "{{ nginx_source_path }}/nginx-{{ nginx_version }}.tar.gz"
    timeout: 30  # 增加超时时间为 30 秒
    mode: '0644'
  throttle: 1  # 限制同一主机上的任务并发数为 1

- name: Extract Nginx source
  unarchive:
    src: "{{ nginx_source_path }}/nginx-{{ nginx_version }}.tar.gz"
    dest: "{{ nginx_source_path }}"
    remote_src: yes
  throttle: 1  # 限制同一主机上的任务并发数为 1

- name: Configure, compile, and install Nginx
  shell: |
    cd {{ nginx_source_path }}/nginx-{{ nginx_version }} && \
    ./configure {{ nginx_configure_options }}
    make && make install
  throttle: 1  # 限制同一主机上的任务并发数为 1

- name: Create systemd service file
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx@{{ inventory_hostname }}.service
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  notify: restart nginx