# nginx-mng/tasks/conf_setup.yml
---
- name: Create Nginx configuration directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ nginx_conf_path }}"
    - "{{ nginx_conf_path }}/conf.d"
    - "{{ nginx_log_path }}"

- name: Configure main nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}/nginx.conf"
    mode: '0644'
  notify: 
    - validate nginx config
    - reload nginx

- name: Configure host-specific configurations
  template:
    src: "{{ inventory_hostname }}-nginx.conf.j2"
    dest: "{{ nginx_conf_path }}/conf.d/nginx.conf"
    mode: '0644'
  notify:
    - validate nginx config
    - reload nginx
  ignore_errors: yes

- name: Ensure proper permissions
  file:
    path: "{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    recurse: yes
  loop:
    - "{{ nginx_conf_path }}"
    - "{{ nginx_log_path }}"