---
- name: 启用EPEL软件源
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: 安装编译依赖项
  ansible.builtin.yum:
    name:
      - gcc
      - make
      - openssl-devel
      - pcre-devel
      - zlib-devel
      - glibc-devel
      - kernel-headers
      - libxcrypt-devel  # 根据系统版本调整包名称
    state: present