---
- name: 检查备份信息文件是否存在
  ansible.builtin.stat:
    path: "{{ nginx_install_dir }}/backups/last_backup.yml"
  register: backup_info_file

- name: 读取备份信息
  ansible.builtin.include_vars:
    file: "{{ nginx_install_dir }}/backups/last_backup.yml"
    name: nginx_backup
  when: backup_info_file.stat.exists

- name: 备份当前版本（回滚前）
  ansible.builtin.command:
    cmd: cp -r {{ nginx_install_dir }}/{{ inventory_hostname }} {{ nginx_install_dir }}/backups/pre-rollback-{{ inventory_hostname }}-{{ ansible_date_time.iso8601 | regex_replace(':', '-') }}
  register: pre_rollback_backup
  changed_when: pre_rollback_backup.rc == 0
  when: backup_info_file.stat.exists

- name: 恢复之前的Nginx版本
  ansible.builtin.command:
    cmd: rm -rf {{ nginx_install_dir }}/{{ inventory_hostname }} && cp -r {{ nginx_backup.backup_path }} {{ nginx_install_dir }}/{{ inventory_hostname }}
  register: rollback_result
  changed_when: rollback_result.rc == 0
  when: backup_info_file.stat.exists
  notify:
    - restart nginx

- name: 更新当前版本记录
  ansible.builtin.copy:
    content: "{{ nginx_backup.version }}"
    dest: "{{ nginx_install_dir }}/{{ inventory_hostname }}/current_version"
    owner: nginx
    group: nginx
    mode: '0644'
  when: backup_info_file.stat.exists

- name: 回滚失败提示
  ansible.builtin.fail:
    msg: "没有找到Nginx备份信息，无法执行回滚操作。请确保之前已经执行过升级操作。"
  when: not backup_info_file.stat.exists恢复之前的Nginx版本