---
- name: 创建nginx用户和组
  ansible.builtin.user:
    name: nginx
    system: yes
    create_home: no
    shell: /sbin/nologin

- name: create nginx install dir
  ansible.builtin.file:
    path: "{{ nginx_install_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'