---
- name: restart
  systemd:
    name: "{{ service }}@{{ inventory_hostname }}"
    state: restarted
    daemon_reload: yes
  become: yes
  listen: "restart"

- name: reload
  systemd:
    name: "{{ service }}@{{ inventory_hostname }}"
    state: reloaded
  listen: "reload"


- name: validate nginx configuration
  command: "{{ install_dir }}/sbin/nginx -t"
  register: nginx_validate
  listen: "validate nginx config"