---
# 初始化
- name: 启用 EPEL 仓库
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: 安装编译依赖
  package:
    name: "{{ build_dependencies }}"
    state: present
  become: yes

- name: 创建MySQL组
  group:
    name: "{{ mysql_group }}"
    state: present
  become: yes
  
- name: 创建MySQL 用戶
  user:
    name: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
#    system: yes
    shell: /sbin/nologin
    create_home: no
  become: yes

- name: 创建安装目录
  file:
    path: "{{ mysql_install_dir }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: 0755
  become: yes
