---
- name: 下载MySQL源码包
  get_url:
    url: "{{ mysql_source_url }}"
    dest: /tmp/mysql-{{ mysql_version }}.tar.xz

- name: 解压源码包
  unarchive:
    src: /tmp/mysql-{{ mysql_version }}.tar.xz
    dest: "{{ mysql_install_dir }}"
    remote_src: yes

- name: 初始化数据库
  command: "{{ mysql_install_dir }}/bin/mysqld --initialize-insecure --user={{ mysql_user}}  --basedir={{ mysql_install_dir }} --datadir={{ mysql_data_dir }}"
  become: yes

- name: 加载mysql配置
  include_tasks: config.yml

- name: 加载服务配置
  include_tasks: service.yml

- name: 初始化数据库
  include_tasks: setup_db.yml

- name: 配置备份任务
  include_tasks: backup.yml