---
# 主入口文件
- name: 执行安装阶段
  import_tasks: install.yml
  tags: [install]

- name: 执行配置阶段
  import_tasks: config.yml
  tags: [config]

- name: 管理服务状态
  import_tasks: service.yml
  tags: [service]

- name: 初始化数据库
  import_tasks: setup_db.yml
  tags: [setup_db]