---
# 主入口文件
- name: 记录执行前的版本信息
  import_tasks: get_version.yml
  tags: [always]

- name: 初始化
  import_tasks: init.yml
  tags: [install]

- name: 执行安装阶段
  import_tasks: install.yml
  tags: [install]

- name: mysql配置更新
  import_tasks: config.yml
  tags: [config]

- name: msyql systemd服务配置更新
  import_tasks: service.yml
  tags: [config]

- name: mysql备份
  import_tasks: backup.yml
  tags: [backup]

- name: 记录执行后的版本信息
  import_tasks: check_version.yml
  tags: [always]