---
# 服务管理任务
- name: 创建systemd服务文件
  template:
    src: mysql.service.j2
    dest: /usr/lib/systemd/system/{{ mysql_service_name }}.service
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: 0644
  notify: restart mysql