# nginx-mng/handlers/main.yml
---
- name: restart nginx
  systemd:
    name: nginx@"{{ inventory_hostname }}"
    state: restarted
    daemon_reload: yes
  listen: "restart nginx"

- name: reload nginx
  systemd:
    name: nginx@"{{ inventory_hostname }}"
    state: reloaded
  listen: "reload nginx"

- name: validate nginx configuration
  command: "{{ nginx_install_dir }}/sbin/nginx -t"
  register: nginx_validate
  listen: "validate nginx config"

- name: 重新加载 systemd 配置
  systemd:
    daemon_reload: yes
  become: yes
  listen: "daemon_reload"