---
install_dir: "/usr/local/{{ ex_service }}/{{ inventory_hostname }}/{{ ex_service }}"
conf_dir: "/etc/{{ ex_service }}/{{ inventory_hostname }}"
data_dir: "/data/{{ ex_service }}/{{ inventory_hostname }}"
log_dir: "/var/log/{{ ex_service }}/{{ inventory_hostname }}"
version_log_dir: "/var/log/version_log/{{ ex_service }}/{{ inventory_hostname }}"
backup_dir: "/data/backup/{{ ex_service }}/{{ inventory_hostname }}"

# Backup settings
max_backups: 10

# 编译依赖
build_dependencies:
  - make
  - pcre-devel
  - zlib-devel
  - pcre 
  - zlib 
  - openssl-devel
  - gcc
  - gcc-c++
  - libaio
  - numactl-libs
  - ncurses-compat-libs