---
install_dir: "/usr/local/{{ service }}/{{ inventory_hostname }}/{{ service }}"
conf_dir: "/etc/{{ service }}/{{ inventory_hostname }}"
data_dir: "/data/{{ service }}/{{ inventory_hostname }}"
log_dir: "/var/log/{{ service }}/{{ inventory_hostname }}"
version_log_dir: "/var/log/version_log/{{ service }}/{{ inventory_hostname }}"
backup_dir: "/data/backup/{{ service }}/{{ inventory_hostname }}"

# mysql
port: 3306
mysql_bind_address: 0.0.0.0
mysql_databases: []
mysql_users: []
mysql_root_password: "{{ vault_mysql_root_password }}"

# Compile options
nginx_configure_options: >
  --prefix={{ install_dir | dirname }}/{{ version }}
  --user={{ user }}
  --group={{ group }}
  --with-http_ssl_module
  --with-http_v2_module
  --with-http_realip_module
  --with-http_stub_status_module
  --with-pcre
  --with-threads

# Backup settings
max_backups: 10

# 编译依赖
build_dependencies:
  - make
  - pcre-devel
  - zlib-devel
  - pcre 
  - zlib 
  - openssl-devel
  - gcc
  - gcc-c++
  - libaio
  - numactl-libs
  - ncurses-compat-libs