---
- name: Nginx 安装/配置更新/nginx升级/回滚
  hosts: nginx_servers
  become: yes
  vars:
    nginx_upgrade: false
    nginx_new_version: "1.25.4"      # 要升级到的版本
    nginx_rollback: false
  roles:
    - nginx-mng